algoritmo "Estrutura para-faça"


var
   soma:inteiro
   cont:inteiro
inicio

   escreval("=============================================")
   soma<-0
   escreval("Contagem: ")
   para cont de 10 até 1 passo -1 faça
      escreval(cont)
      soma<- soma + cont
   fimpara
   escreval(" ")
   escreval("A soma é: ", soma)
   escreval("=============================================")

fimalgoritmo