algoritmo "Exercício Proposto"

var
nome:caracter
n1,n2,divi,multi,sub,soma:real

inicio
escreval("Nome do Usuário: ")
leia(nome)
escreval("Primeiro Número")
leia(n1)
escreval("Segundo Número")
leia(n2)
soma<-n1+n2
escreval("Soma: ",soma)
sub<-(n1-n2)
escreval("Subtração: ",sub)
divi<-(n1/n2)
escreval("Divisão: ",divi)
multi<-(n1*n2)
escreval("Mutilicação: ",multi)





fimalgoritmo